mullvad:
    account: ENC[AES256_GCM,data:ldSDZKbllt0DM/DAYHZtrA==,iv:M/Ef9Zga2LpvtaVQwwS6E6SyjguUl7gfeA5malx52mw=,tag:3OFTpp6PwdxRmY8TDZ6lHw==,type:str]
    device: ENC[AES256_GCM,data:3e3DdE2lbF+Dt3A=,iv:kRaG3EI07BM7gmPlYjgohSIT6SNz0Qnx5RjrO5yXuQY=,tag:KT9K22TOUx7RIkHbnI0rVg==,type:str]
    privateKey: ENC[AES256_GCM,data:P8vnrgbmOmNrA2kyipY+6Ej3Ryot9VUIuM9p6XcKizoEZ8evQ98VdIyG/sM=,iv:5Z2/UIi2wsnE02Ah0DwOxTlUka/iKPFDsxbCZDn7Ri4=,tag:kGsNNYWbQbFw62Q9Ua62KA==,type:str]
    server: ENC[AES256_GCM,data:tHUqIyNLGgsIfo4AVg==,iv:5GrIFHUCUfgYBYrJFmq0+ABeRQXSl7vCAsrOeoVvafg=,tag:lWR+I/uVOtUEzSRN+rnW1Q==,type:str]
upsmon:
    password: ENC[AES256_GCM,data:zTSZxjBFX0YFLfF9Aoe6mbSZYgS9Elq4tA==,iv:AFLrdS39AFRJYY/Fs9JblAgPmAMQrJ4d4VMfNedyNBg=,tag:r7reUSZGyycmJq7H8sSHWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lj4gknnm9yxtcj8z279rnf2cya9kqt4pr28yca3cc9ejgcl9uqfsldn2r6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVG5VWDZTUzZMU21TM1Jt
            R3h1Qk1yQTE1RDBjV0p0NWc3QTVJd0txQlM4ClVoTkNwWXh2VlpCY0RyNzRVaXpW
            cVZHcXNLQS9GV3FQeWgyZUJEL3RjdW8KLS0tIDlwNURKS3JEUmdBVlYzU3BDSTdR
            QWRtdDdOWTNmTDg0TG1HdjE2UWlqNVkKzcEsABqXDgUk5eMwX+641Jrt4hNiNBsS
            7r2Z/Hu3dC3L2Wiw6EOoCVirjNUyDompmARZ6Y5/SjdReeeKXg1U6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14m320dsll0pnxfzxespkkyqj8mdu9v6curvank8ayje77v3jypvsylh6rq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WVVhK0FzYjVGRjlEeGJP
            UHF6WmU3U25UL25EdlVHRENYY29GakRHOEI0CndWUW54ZlBPb1dDbm1TZFJLanM2
            K0ZJdENXV0tYREFCeWc2aXdsTzBBVUkKLS0tIFNmaGdBbmRJanNMcFpybnJ1QVZq
            V2h2djc0SlZaaVZFVWVwU2RST2ZldEkKsvxt43arWhQYEFAChefPjo5RZ0inkSH5
            zsqXa69l4yLE/2AgiK1aaZ8Je6I3hNPFhdYOakBaVAS4+bV2acm2TA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ywld2dxh2mdhqdcgd5ne7yypla74n52dhu9cw0ccsgpfrgg6drqysguje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZnVFcVlyUDJPTHJyMVJu
            S0lrTjdEMnhNK0p1Uk9URGZ2aWJZSUFHT2xzCjdYT2xBS0lOTzR6aENYSkVjZDRy
            RHlXQkNza2E5ZlprZnRuRE92em1GbmsKLS0tIFdGY0RTeDl1dFRPRTdnd3pBblRS
            M0tmMis1WHMrZGJhbHUyWWxmOHdPN1UKyXupNzNx5yaiMfjddB9fad53IgrKyowx
            w2aY3ZM8pBqEUQGuf0Wh+aheUUXguIxFqNM38TdQQvA+EB3LQ1/KpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T01:44:39Z"
    mac: ENC[AES256_GCM,data:sedkmhlJQVnHSpCS2O1t4nw+QPyuMw74NuIXZkYsjiMPS1dImH9p94nZid/IOYQ/XhWIdmU6zst1jpnkCjluKY3FkuerQyQr00XGZ/HEDzBZPiNHSTmob5KTQZz/GiFXm6d5xBokc4GUzvCwZMLTk7AsU7b+gipo0Sjl07T6bY4=,iv:mnPvgE6Dvpxd6E2egTnpsI7gzy5EJxhewgqMaAzjk1g=,tag:XbYYPsI9H/v5aI/X5SKjTw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
