mullvad:
    account: ENC[AES256_GCM,data:ldSDZKbllt0DM/DAYHZtrA==,iv:M/Ef9Zga2LpvtaVQwwS6E6SyjguUl7gfeA5malx52mw=,tag:3OFTpp6PwdxRmY8TDZ6lHw==,type:str]
    curly:
        device: ENC[AES256_GCM,data:iaibKeNN5+OsKkRFsg==,iv:biLpxrr6Jf8JAX81eoF4sO6qVBTeCfpfrok4b+hVOVw=,tag:PiAojjrJWLLXbqLAD9CeRw==,type:str]
        privateKey: ENC[AES256_GCM,data:B+DRTsXPcTHw/TzjjxNRlqyYQcfgHSNzbhwpR0I1r2m5976vaBEzrdl8KKQ=,iv:ismTZGH9C4bw/Dzl1YcMSt3Cre6IhCnVL9Dj/JfbJ+Y=,tag:HOipZTM5f4JpxWVHfoMIDg==,type:str]
    mii:
        device: ENC[AES256_GCM,data:1m7jneoHsEINxNT12Q==,iv:/2Ynx1Ppj6YriIiJm3ZPg0YiIH/lMFP6Q2qdwmMJwJQ=,tag:pnGBvElsiFtDpkKcZDbdYg==,type:str]
        privateKey: ENC[AES256_GCM,data:L/5m/zkgi/TIReaGUe+vaeItn5URbdtDLMMHQCJK5GJAln/WLEGbv00g54M=,iv:i3zkGZLInpwiBzEzNqOpuSnvpbivzv4BIluf7GXpzkw=,tag:r2ZVUJWmhTQEoUbZAa4oQg==,type:str]
    server: ENC[AES256_GCM,data:cnh11K6R//knyNkAng==,iv:I966lYtkMNUazR59y3wxAvB9hXv5Gza162mEx3PvJks=,tag:vCbiTxhS7t/ppx0JeJ018Q==,type:str]
    socksAddr: ENC[AES256_GCM,data:NDAX5Au3pu0vdoHuZOPQ,iv:HUSwKK+u2DFLT86Bz4Ug1Pds5JCHnHS+4yzoAn1O4xs=,tag:l6uHBwAU+NuDxxwugLm+2g==,type:str]
upsmon:
    password: ENC[AES256_GCM,data:zTSZxjBFX0YFLfF9Aoe6mbSZYgS9Elq4tA==,iv:AFLrdS39AFRJYY/Fs9JblAgPmAMQrJ4d4VMfNedyNBg=,tag:r7reUSZGyycmJq7H8sSHWw==,type:str]
u2f:
    authMapping: ENC[AES256_GCM,data:+BKQz8ZPB4AgVNBWaDBLYcgX4htWtvFoNcsz0Vkl89u0un8f7groskO7P97cjTdHonUnvUeAL6pWjEveXMzy0UNllRNvQjeW3yYZzOukZtRO7QDyIEMZOnaCvWNWe0nPFfLt3hODGr9iFmoUv2UI77ly8rsw3tejAqt5Lgl6e7L1UDFYD0ANTjWuyGyJvdWqx96YOF+DAknKGAwgnbtVKFrpaI0sAdKHIO01ZtDW3Ea0W4mLAqSvDtG0In81Mbi0FnwLwLPJ5rz8Df4eKdOP688Rk+/5dpi7wrqZCtTK2V+pXACOVUCL40d85VvLK+uzUtaXHDx9SdX3/+a+wGlwcos1FDHh/QqQaOma4jHhMXgQEM76mVrT2aBbLEnQ8mk6L9X68l1nvmVJB+wEWdbvyzJATwaKOP0woDwXBaTCgC0sQ2nEV2rMxL83W0iVitxMbN/H18RgKd8fbiiGaQMzJ6b17ZzhHtM8AfdTW1LHy/hRffgy1sql1c59JuVSuBwj4KENsBREvcTi+zRIqvHsvyU8fYcrzKJRU7Apg9QAk/PgpF4PrZho4XSB9WhYneofF4wku766lSpPAdkLFf0r/CDSue9on+8fmkQ17ZV9+isrGLBthbnVIhkyFZRpBCNRRHv44XbgZb+h4O5TQJufo0kfjnDLSHts8+fQAnhi8iK8X+jgLOfIvPwRFfuKDKOIfvMNbK1tsX/3LbfU2QBGj8zMZ2opyo4/06KYX04unGyAnN2AeGC6lEtAg2Q+DHqZJzJfonnpokTAS1h/CA==,iv:p80AWpmJzmU6pXZWguw+MgVsl7gwp76VnrBHwU9SvKM=,tag:GtM5rWwaG0j16z+yIuVcHQ==,type:str]
sops:
    age:
        - recipient: age1lj4gknnm9yxtcj8z279rnf2cya9kqt4pr28yca3cc9ejgcl9uqfsldn2r6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTERobnBJN2wyaGRuMVR6
            aXRkSFc3d0R0bVAySDNUa3ExMFpYaHhxRjFFCjM3WjlWM1h4eFRwb1U3VXhJUWpC
            OXlMK2xpYWIvaTB0OVcvejQ3SEt0NkEKLS0tIHIyYzdDcEVJaWdGTUVmTm5meXJO
            VHZwVWlGeVRqbktqZzdKdTJxOE5qM0UKobiFc0316gdSonxlNPHEevhMDSEiISbW
            tqErtNn7hplAofNSAhX4ZYemUfh/c1t7vdzzdfOfaia4BOFpNImDsg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14m320dsll0pnxfzxespkkyqj8mdu9v6curvank8ayje77v3jypvsylh6rq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RU9hVVNIVVNCUi9IWXBk
            c1M4OHVydFZwQzljc2hVT1dxSFd3UDdvWVJNCnVsZHpka0NLcExsVmEyYmpML3g1
            QVRxdHdLVC9yZGtiRTUzMExEbXFtNTAKLS0tIEJ3TkxLeGJDamFRS2NYRngrNU1o
            VkZISWNzY2JZSWx3aWFCTzJGWG1HQzQKvLqSZbSCH2rNLIhVmvjDI6MH+VA3WZsY
            qHL2Aw5wIa5hTubs63XfFdCPiy9e8oYtVf6u4pXrQoeycQLWucoWoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ywld2dxh2mdhqdcgd5ne7yypla74n52dhu9cw0ccsgpfrgg6drqysguje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WDVVeWJiU2xHOHZFaW1z
            WnVsNDE5MHZqOHBSK3dOSmVzcDkrL1V3RDJvCmw5bGVtQ09IWUdWaFU2Y0N0UUVv
            OFZRTzFlMzRmQ3VYNWRKM3lkdDhLcFUKLS0tIE9WemxRMnNUKytKTmpMM2dxTlpW
            Y2xNMDJDUnFTMXpMODVTK0VKYkpGZDQKuwBWfzVt+0fASbMxUW0F/ghvVwZMQC1i
            /Xmi5P17wuUY6hggoce88fqgujL6KjyCnYpVc3BnYQvksSsBH2knKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mu2mdl9zlh3wg8p6e4tlavygj8afrl53nfk6kc6xc8gxj4dgaszsk945l7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3T2ZoQ1NPN3Q5Y0dPMDY5
            clZqWUliVmxKY0VHdVVmTjB4Y1BIcHRzT1VrCnFXRDdVOFBuM2k1N3BZTjBkQmpu
            eGNMOXJIOFdERDRDKzNxNFhvdm9tc28KLS0tIDA2d0d6Zys5YnFwajlIajlMUnJK
            dXEwYVIrYlZLK0ZOdXZBY0tPSWhDb2sKMrUqJYORUjRajy/zjQ/svFDlml0hsZuv
            3uA36Ha7zfpgSCb2lYcWtw/qPAqmqnXx3IL/15wbNd/eO2N7Xmq1ZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n4dwsud2maqvad6xz5kytq8vj7qlqcuukxslshch6r9pn8ljreqsysa8gj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdlQwelJ0SmNiMGFFeWtE
            MEFoR2dxTkpjcndtM0dmSW11WGJjK0JBMXh3Cm5Gc3YzMlJtZWZScFlYeTJhYjhS
            djF0MURlbzhpczlGNFFqRElhL216WkEKLS0tIFZCd3Zna2dPdnJhZHU1TG5BS3p1
            T09GNGdsUmY0Wkl3UWg2WDFqa0xYVWMKplqNMFcSUwBWkpS/kZ5FiV0iIAdANizY
            yeVaUNV4FrlElgrXTljoQTRU5kjp8H+cG9I0af2STxFTjCyrg2x/Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T00:59:18Z"
    mac: ENC[AES256_GCM,data:mH6YkzQQIV0a4n6Llk6HynsaU8CjQK308ilgU+IsOcuDlomL4c2bVkkKBJZC2mYItGUG/uFDKQHcWktzpgiAWPl/pFy3/GWkPhpEqd21HQVozbC+ZLMuOnayIi1UrOSJsvX+APW0jANaPdL54XWvXWsLbu7mHuNm4oz1p1rWhR8=,iv:Lbaea/KX5uZrqcNiyIIF3UqpDYapFuqpRU0O0jz1jZY=,tag:izGfP4oA44+Q8sdwg9xfGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
