mullvad:
    account: ENC[AES256_GCM,data:ldSDZKbllt0DM/DAYHZtrA==,iv:M/Ef9Zga2LpvtaVQwwS6E6SyjguUl7gfeA5malx52mw=,tag:3OFTpp6PwdxRmY8TDZ6lHw==,type:str]
    device: ENC[AES256_GCM,data:3e3DdE2lbF+Dt3A=,iv:kRaG3EI07BM7gmPlYjgohSIT6SNz0Qnx5RjrO5yXuQY=,tag:KT9K22TOUx7RIkHbnI0rVg==,type:str]
    privateKey: ENC[AES256_GCM,data:P8vnrgbmOmNrA2kyipY+6Ej3Ryot9VUIuM9p6XcKizoEZ8evQ98VdIyG/sM=,iv:5Z2/UIi2wsnE02Ah0DwOxTlUka/iKPFDsxbCZDn7Ri4=,tag:kGsNNYWbQbFw62Q9Ua62KA==,type:str]
    server: ENC[AES256_GCM,data:tHUqIyNLGgsIfo4AVg==,iv:5GrIFHUCUfgYBYrJFmq0+ABeRQXSl7vCAsrOeoVvafg=,tag:lWR+I/uVOtUEzSRN+rnW1Q==,type:str]
upsmon:
    password: ENC[AES256_GCM,data:zTSZxjBFX0YFLfF9Aoe6mbSZYgS9Elq4tA==,iv:AFLrdS39AFRJYY/Fs9JblAgPmAMQrJ4d4VMfNedyNBg=,tag:r7reUSZGyycmJq7H8sSHWw==,type:str]
u2f:
    authMapping: ENC[AES256_GCM,data:nzJQnWL8lkC7lK4L6CKWHf33xPhzn+gyfxSR2Pr/PmCqYVw3ULMCvlCf0v87D06hcxYWrGypgh3Ac3W4tcexKKxS+D2p+RuSXpQAVp+L6yAcHetW6DsZWz9WjOUK+DIumshFwCaRLgyNx+DXfDapuud0EwVrbQIQ444OU07K6l/5qT7FC1nobPIIsggASJ1uJcjC+7NIn20Ch7ITJp1l3I7yU4iYjw4AZl7u8b5mNjuT+81YpiVaCtOrBv6SW17pIZaMAmhNvTx5dvGDiYm1hLBZyoyoBcPoYpqPruTkNbm3akYDv8cPKoX/o5/PhUTWXTCfjJqEP4KCXZSc0lSzRdwyh5EaQPZYRU2IJANhNi8QK1TyG/se3z0/J4hYOpM3NYQ5moaVgJ6JEhuC4JhuMow/qQ2FurMhyymlzgI1W3HbStyY6TNrZhyu5Ys1RqrmCnqVkRL2yyOz5NjiER5iXBviOyb2/XkdSDNhTPiWR/GLx04zx03agA2NOsPjYlWswhaadM3JdJNCIytveW61nd5G5s72SicePwR3aamEeSgSB6FAB6huzbVLAzxGO9AmVRw8thd2WpsFT2c9Cgo6kFsZXt2tt1NnB8wo9cexTBrBPbAIEQX9qfNkZeb6mgOjJupTyd0tQ77icpi58p6xQ8W3SDLaNUKa44RMBLAgVJLIpKrNoF2v6SgN3LlQRo6DG71QqGkV4ouy6vyF6m1Z18Fzw3gIsxK36ykVAg/Dt4PXewZ5vNqf06xY7f3oZ4ttaRxROvSWTIXU7e1cWRBWINeAjwrjxpwfHy0Kb7D+452rmCU4kA==,iv:KaCdThVZv2bildQOqmuhJKVZpYXRKKPoYPV1Hs3v6tQ=,tag:6a0XGoM3/oJbDr5zyLUsDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lj4gknnm9yxtcj8z279rnf2cya9kqt4pr28yca3cc9ejgcl9uqfsldn2r6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMkJyZE1KcDQrdXl5OEVH
            VXArOWVXVzFGcEVsVDAwaG83S2JjU09WRlc4ClZmOVlkUDhVL2NJdmNwSndsVlNj
            YmFHQmlYbmllVTF1dEFVb1MwWnN2UTAKLS0tIDBNSXBwUUkvRkxQbUloZ292eEVJ
            R2hlakxteTl3YWVmY0wrcmJFemJvY0EKZbq5/VCpgnyMmy9qIiIT2xWJq2NvbsHY
            tOOVEQFYiEsOxQWosLcgJxFgdtHWtafFvk1KH5W1alGTWwHFSGNbjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14m320dsll0pnxfzxespkkyqj8mdu9v6curvank8ayje77v3jypvsylh6rq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNk53RDFRRUUrNnQwV2Z3
            SjFSbWsxd3lRUzNUaTJGcjlDbVZJTi9WK1Z3CmJDWWh4QzhRcDZVcnZZYkhpUEtu
            TVZzTDF5ZzkyQnRSZ2xSNm5tUVpmRjQKLS0tIEx0NktTQTNKNTM2dG0wa2JtM0RS
            NmdaeDlSWW5LT25ZbTB0MGQrMkFzWWcKIPej2Fs+jXWQUWn26IKvWIyWaQd6osg8
            iBo8GzFP1xA7+9cdVu7/9NjQqEH+ibE5UJ0bwCQjZ7SneJhJvT7NJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ywld2dxh2mdhqdcgd5ne7yypla74n52dhu9cw0ccsgpfrgg6drqysguje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc0F1VWMrZlBaTGZXaU5p
            OWRreWY2Tk9MSm5acXlvTzF5a2ZqcVlaRURnCkF5ZEttQmpUUDRTVWgwUXNRSG5T
            eWFwSTRjL0NzWjV6Ymc0UUZEeXBlcUUKLS0tIHdLRmhCSFBrNlozbnFtb3pOb2lY
            VGthb3kzRjNMZVhCYWNpY2RBZDhEclkK4UqdRBM4aajKIMxjyhU/um99ZZW/lr83
            6fiASKj5nPn8JDgB142leARu8vp8YNnI5a629ce4eqULdI2SsG0ipw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mu2mdl9zlh3wg8p6e4tlavygj8afrl53nfk6kc6xc8gxj4dgaszsk945l7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdjRJY0Y5Q0ZOMGFhL01s
            UmtQa0lRRVBoWGEybFN6NXRBZmRrSlRqNmxBCjNwanNiYm5TQ2RRbzhMQ04wK0kx
            MXMzSzBvRzRCbjA0aUVsVGk1L2dXN0UKLS0tIEJrbFp4ZUl0L3hiWGdmeVZnTW85
            TkJXNVoyNEJpVjZaRTN3eXR3SWcyNG8Kl9GdCdLOc9zK+PlK5qM55FW9VFiwZg3J
            nUQYvsRwD+zHa2OHxBD7HX50i7UR/M19fKC8/HLe50fmLX+ZLOw0ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-13T04:29:34Z"
    mac: ENC[AES256_GCM,data:SRJV7XPQ2V2NgSrBNukJjUUGEsVW5DsGjGQKcZ9H1IGjAe9Ue6kZMNuyZj0LiUJ7nWNw2nuLLc5h3mHzyydCX987EsAa1Es/JrgZSjGhc7FuEXyYucDGTG1a/MebrIbF7KeFuETKgAh4AUdRRk/Eejrys4cUOcDpjQ87UdRYN50=,iv:LnL4DilB9aNV07b53MQiz1j8MLI/fsmuPlXs9FGMtmo=,tag:kAqg3NSK5IVRPoLmWXO3sQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
